spring:
  application:
    name: bonus
  datasource:
    url: jdbc:postgresql://localhost:5432/bonus
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
